---
# Project Information
site_name: backfillz-py
site_author: Roly Perera
site_description: MCMC visualisations package developed at the University of Warwick and supported by the Turing Institute.

# Repository information
repo_name: rolyp/backfillz
repo_url: https://github.com/rolyp/backfillz
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Roly Perera

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rolyp
      name: rolyp on GitHub

# Page tree
nav:
  - Home: index.md
